# Generated by Django 4.1.1 on 2022-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
