# Generated by Django 4.1.1 on 2022-09-15 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(upload_to='photos/%Y/%M/%D/')),
                ('is_active', models.BooleanField(default=True)),
                ('publish_data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
